# Generated by Django 4.2.1 on 2023-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LekiRefundowane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.IntegerField(unique=True)),
                ('substancja_czynna', models.TextField(default='')),
                ('nazwa', models.TextField(default='')),
                ('postac', models.TextField(default='')),
                ('dawka', models.TextField(default='')),
                ('zawartosc_opakowania', models.TextField(default='')),
                ('ean', models.BigIntegerField()),
                ('grupa_limitowana', models.TextField(default='')),
                ('cena_hurtowa', models.IntegerField(default=0)),
                ('cena_detaliczna', models.IntegerField(default=0)),
                ('wysokosc_limitu', models.IntegerField(default=0)),
                ('zakres_wskazan', models.TextField(default='')),
                ('poziom_odplatnosci', models.CharField(default='', max_length=10)),
                ('wysokosc_doplaty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LicznikWyszukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.IntegerField(unique=True)),
                ('ctr', models.IntegerField(default=0)),
            ],
        ),
    ]
