# Generated by Django 4.2.1 on 2023-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaneLeku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.BigIntegerField()),
                ('grupa_limitowana', models.TextField(default='')),
                ('cena_hurtowa', models.IntegerField(default=0)),
                ('cena_detaliczna', models.IntegerField(default=0)),
                ('wysokosc_limitu', models.IntegerField(default=0)),
                ('zakres_wskazan', models.TextField(default='')),
                ('zakres_wskazan_pozarejestracyjnych', models.TextField(default='')),
                ('poziom_odplatnosci', models.CharField(default='', max_length=32)),
                ('wysokosc_doplaty', models.IntegerField(default=0)),
                ('data_rozporzadzenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LekRefundowany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.IntegerField(default=0)),
                ('substancja_czynna', models.TextField(default='')),
                ('nazwa', models.TextField(default='')),
                ('postac', models.TextField(default='')),
                ('dawka', models.TextField(default='')),
                ('zawartosc_opakowania', models.TextField(default='')),
                ('ean', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicznikWyszukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.BigIntegerField(default=0, unique=True)),
                ('ctr', models.IntegerField(default=0)),
            ],
        ),
    ]
