# Generated by Django 4.2.1 on 2023-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optymalizator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekirefundowane',
            name='lp',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='lekirefundowane',
            name='poziom_odplatnosci',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='licznikwyszukan',
            name='lp',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
