# Generated by Django 4.2.1 on 2023-05-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optymalizator_app', '0002_alter_lekirefundowane_lp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LekiRefundowane',
            new_name='LekRefundowany',
        ),
    ]
